# Generated by Django 5.0.6 on 2024-06-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
