# Generated by Django 5.0.6 on 2024-06-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steno_simulator', '0003_user_auth'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_auth',
            table='user_auth',
        ),
    ]
